version: "3"

services:

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: maeddi
      MYSQL_PASSWORD: maeddi
      MYSQL_DATABASE: api_db
      
    ports:
      - 3306:3306

  api_server:
    image: fastapi_app
    #build:
    #  context: .
    #  dockerfile: ./Dockerfile
    ports:
      - 8000:8000