apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mysql.name }}
  labels:
    app: {{ .Values.labels.app }}
spec:
  type: {{ .Values.mysql.service.type }}
  ports:
    - port: {{ .Values.mysql.service.ports.port }}
  selector:
    app: {{ .Values.labels.app }}
    tier: {{ .Values.mysql.labels.tier }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.fastapi.name }}
  labels:
    app: {{ .Values.labels.app }}
spec:
  type: {{ .Values.fastapi.service.type }}
  ports:
    - port: {{ .Values.fastapi.service.ports.port }}
      nodePort: {{ .Values.fastapi.service.ports.nodePort }}
  selector:
    app: {{ .Values.labels.app }}
    tier: {{ .Values.fastapi.labels.tier }}