
name: CI

on:
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  image-build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: GCP auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCR_JSON_KEY }}
      
      - name: Build docker image
        run: |
          docker build -t grc.io/socar-dev/maeddi-server:latest onboarding/gke_dev/Dockerfile
      
      - name: Publish
        run: |
          docker push grc.io/socar-dev/maeddi-server:latest
