
name: CI

on:
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  image-build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: login GCR
        uses: docker/login-action@v2
        with:
          registry: gcr.io
          username: ${{ secrets.GCR_JSON_KEY }}
          password: ${{ secrets.GCR_JSON_KEY }}
